### ISSUE TITLE
StackPointer的疑问

### ISSUE THREAD

**Issue by ThisisLiuNan** [dzh/coca#1]
StackPointer的作用是什么？作为读写操作的封装嘛？
StackPointer.reverse()方法为什么index的操作是 index-2 这里是默认只有两级缓慢嘛
![Uploading image.png…]()

**Comment by dzh** [comment]
@ThisisLiuNan 嗯，StackPointer定义读写行为。reverse里的-2是因为`rp.next()`后index在下一个索引位置，那么-1回到当前位置，再-1到需要操作的位置。同理，+2。和几级缓存没关系，可以任务级

**Comment by ThisisLiuNan** [comment]
哦哦，我理解偏差了...还以为是要把栈做翻转.
